### ISSUE TITLE
Sorry to bother you but I need some help

### ISSUE THREAD

**Issue by kingiluob** [Ushio/SimpleImageCompareTool3#1]
I am a beginner at phiscial based rendering.
I have read your article about implementation about microcylinder appearance model for cloth at https://ushiostarfish.hatenablog.com/entry/2019/01/02/161716
you have done a great job ! I read some of your code but still confused with the process.
I have read this article http://graphics.ucsd.edu/~henrik/papers/practical_microcylinder_appearance_model_for_cloth_rendering.pdf
and want to go ahead to render the scene. But get confused at some point and caculation. So I am here to ask for some help, could you please help me with sharing your implementation code, or, could you please help me understand the process by answering some questions?
Thanks you so much.

**Comment by Ushio** [comment]
@kingiluob 
oh, I didn't notice you comment. Thank you for reading. here is my test code. 
https://github.com/Ushio/MoodyRender/blob/microcylinder_brdf/common/microcylindercloth.hpp

**Comment by kingiluob** [comment]
> @kingiluob
> oh, I didn't notice you comment. Thank you for reading. here is my test code.
> https://github.com/Ushio/MoodyRender/blob/microcylinder_brdf/common/microcylindercloth.hpp

Thanks for your help. I will check out the program process and try to finish rendering myself. Thanks a lot. I donnot want to just get the coding done but also try to know the rendering process. Might ask some questions later. I will get you know it if I need help,if you are convenient. Sincerely thanks~
